# Generated by Django 2.2.6 on 2019-10-02 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Şərh yaz'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment_user',
            field=models.ManyToManyField(blank=True, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Şərh yazsınlar'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Tapşırığın açıqlaması'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(verbose_name='Tapşırığın bitmə tarixi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tapşırığın adı'),
        ),
        migrations.AlterField(
            model_name='task',
            name='other_user',
            field=models.ManyToManyField(blank=True, related_name='other_user', to=settings.AUTH_USER_MODEL, verbose_name='Tapşırığı görsünlər'),
        ),
    ]
