# Generated by Django 2.2.5 on 2019-09-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190904_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comm',
        ),
    ]
