# Generated by Django 2.2.5 on 2019-09-06 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='other_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
