# Generated by Django 2.2.5 on 2019-09-06 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_task_other_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='other_user',
            field=models.ManyToManyField(related_name='other_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
