# Generated by Django 2.2.5 on 2019-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190911_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=2, max_length=122, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
