# Generated by Django 2.2.5 on 2019-09-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
