# Generated by Django 2.2.5 on 2019-09-13 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_remove_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_user',
        ),
        migrations.AddField(
            model_name='task',
            name='comment_user',
            field=models.ManyToManyField(related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
